name: frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # design packages
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animations: ^2.0.3
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_native_splash: ^2.2.7
  rive: ^0.9.1
  # bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  # additional
  grpc: ^3.0.2
  path_provider: ^2.0.11
  permission_handler: ^8.3.0
  hive: ^2.2.3
  file_picker: ^5.0.1
  equatable: ^2.0.3
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  # color: "#42a5f5"
  background_image: "assets/bg.png"



flutter:
  uses-material-design: true
  assets:
    - assets/svg/playlist.svg
    - assets/bg.jpg
    - assets/flowers.riv