// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: pkg/proto/youtube-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author   string `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Duration string `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_youtube_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_youtube_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_pkg_proto_youtube_service_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Video) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title  string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Videos []*Video `protobuf:"bytes,4,rep,name=Videos,proto3" json:"Videos,omitempty"`
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_youtube_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_youtube_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_pkg_proto_youtube_service_proto_rawDescGZIP(), []int{1}
}

func (x *Playlist) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Playlist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Playlist) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Playlist) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *VideoGetReq) Reset() {
	*x = VideoGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_youtube_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGetReq) ProtoMessage() {}

func (x *VideoGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_youtube_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGetReq.ProtoReflect.Descriptor instead.
func (*VideoGetReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_youtube_service_proto_rawDescGZIP(), []int{2}
}

func (x *VideoGetReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type VideoStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Ready int64  `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Total int64  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *VideoStreamResp) Reset() {
	*x = VideoStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_youtube_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamResp) ProtoMessage() {}

func (x *VideoStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_youtube_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamResp.ProtoReflect.Descriptor instead.
func (*VideoStreamResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_youtube_service_proto_rawDescGZIP(), []int{3}
}

func (x *VideoStreamResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoStreamResp) GetReady() int64 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *VideoStreamResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PlaylistGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId string `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
}

func (x *PlaylistGetReq) Reset() {
	*x = PlaylistGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_youtube_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaylistGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistGetReq) ProtoMessage() {}

func (x *PlaylistGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_youtube_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistGetReq.ProtoReflect.Descriptor instead.
func (*PlaylistGetReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_youtube_service_proto_rawDescGZIP(), []int{4}
}

func (x *PlaylistGetReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

var File_pkg_proto_youtube_service_proto protoreflect.FileDescriptor

var file_pkg_proto_youtube_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x6f, 0x75, 0x74,
	0x75, 0x62, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x61, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x21, 0x0a, 0x06, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x51,
	0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x30, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x32, 0xaf, 0x01, 0x0a, 0x12, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x47,
	0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x38, 0x0a, 0x0e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01,
	0x12, 0x33, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_youtube_service_proto_rawDescOnce sync.Once
	file_pkg_proto_youtube_service_proto_rawDescData = file_pkg_proto_youtube_service_proto_rawDesc
)

func file_pkg_proto_youtube_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_youtube_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_youtube_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_youtube_service_proto_rawDescData)
	})
	return file_pkg_proto_youtube_service_proto_rawDescData
}

var file_pkg_proto_youtube_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_youtube_service_proto_goTypes = []interface{}{
	(*Video)(nil),           // 0: pb.Video
	(*Playlist)(nil),        // 1: pb.Playlist
	(*VideoGetReq)(nil),     // 2: pb.VideoGetReq
	(*VideoStreamResp)(nil), // 3: pb.VideoStreamResp
	(*PlaylistGetReq)(nil),  // 4: pb.PlaylistGetReq
}
var file_pkg_proto_youtube_service_proto_depIdxs = []int32{
	0, // 0: pb.Playlist.Videos:type_name -> pb.Video
	2, // 1: pb.YoutubeGRPCService.VideoGetMeta:input_type -> pb.VideoGetReq
	2, // 2: pb.YoutubeGRPCService.VideoGetStream:input_type -> pb.VideoGetReq
	4, // 3: pb.YoutubeGRPCService.PlaylistGetMeta:input_type -> pb.PlaylistGetReq
	0, // 4: pb.YoutubeGRPCService.VideoGetMeta:output_type -> pb.Video
	3, // 5: pb.YoutubeGRPCService.VideoGetStream:output_type -> pb.VideoStreamResp
	1, // 6: pb.YoutubeGRPCService.PlaylistGetMeta:output_type -> pb.Playlist
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_youtube_service_proto_init() }
func file_pkg_proto_youtube_service_proto_init() {
	if File_pkg_proto_youtube_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_youtube_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_youtube_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Playlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_youtube_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_youtube_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_youtube_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaylistGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_youtube_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_youtube_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_youtube_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_youtube_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_youtube_service_proto = out.File
	file_pkg_proto_youtube_service_proto_rawDesc = nil
	file_pkg_proto_youtube_service_proto_goTypes = nil
	file_pkg_proto_youtube_service_proto_depIdxs = nil
}
